### ISSUE TITLE
Generation problem Ores T12 to T16

### ISSUE THREAD

**Issue by MezzirXIV** [RedGrapefruit09/JustEnoughGems#12]
I have problems when generating worlds with ores from sets T12 to T16. I looked everywhere in the layers indicated in the source folder but couldn't find any, I even used X-Ray software plus the viewer mod but still nothing. Tools, weapons, and armor are well displayed but the generation of ores is not complete. Is there another way to get them other than mining or is it really the generation that has a problem?

**Comment by kanpov** [comment]
The generation is probably the problem. I'll release an update in a few days increasing the generation rates and then it should be fixed. Thanks for your feedback!

**Comment by kanpov** [comment]
@MezzirXIV This issue has been fixed in the v1.2.0 release, which will be available on Modrinth and GitHub shortly.
Please note that v1.2.0 only works on 1.19, so you'll have to upgrade to latest Minecraft.
